# Generated by Django 3.2.16 on 2025-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='amount'),
        ),
    ]
